### ISSUE TITLE
private methods of public class not deobfuscated

### ISSUE THREAD

**Issue by thisisthekap** [BrokenEvent/ObfuscarMappingParser#6]
## Issue Description

Private methods in a public class are not deobfuscated properly with obfuscator default settings.

## Repro Steps

1. Checkout https://github.com/thisisthekap/ObfuscarMappingParser-issue-repro
2. `cd lib`
3. `dotnet pack`
4. `cd ../app`
5. `dotnet run`
3. Use `Mapping,xml` in `lib` project, and the resulting stacktrace of the program execution

### Source stacktrace

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at lib.SomethingFancy.a(String )
   at lib.SomethingFancy.A(String )
   at lib.SomethingFancy.DoIt()
   at app.Program.Main(String[] args) in /path/to/repo/ObfuscarMappingParser-issue-repro/app/Program.cs:line 11
```

### Expected output

```
 System.NullReferenceException. Object reference not set to an instance of an object.
void lib.SomethingFancy.MakeUpperCase(string)
void lib.SomethingFancy.SomeSecretStuff(string)
void lib.SomethingFancy.DoIt()
void app.Program.Main(String[])
```

### Actual output

```
 System.NullReferenceException. Object reference not set to an instance of an object.
void lib.SomethingFancy.a(string)
void lib.SomethingFancy.A(string)
void lib.SomethingFancy.DoIt()
void app.Program.Main(String[])
```

**Comment by thisisthekap** [comment]
To my opinion, obfuscated private methods contained in public classes should be proper deobfuscated.

@preseverence Could you clarify why this behavior is as intended behavior and does not need to be fixed?

**Comment by preseverence** [comment]
:)

**Comment by thisisthekap** [comment]
@preseverence Off topic question: Would it be feasible to migrate 
ObfuscarMappingParser to .net standard and .net core to use it as a cross platform command line util?

This would enable the solution to be used in a much wider range of applications.

**Comment by preseverence** [comment]
I don't understand using .net core for UI tools. It's just meaningless as we will still need WinForms which only exists on Windows. So we will not get it crossplatform but will face other difficulties of .netcore.

As for commandline tool this idea is worth to be considered. What usecase/workflow you imagine it will follow?

**Comment by thisisthekap** [comment]
Use Cases:
* Execute parser on macos and Linux
* Use the parser in internal dev tools developed in asp.net core

I already invested some work, and got a working solution with a .net standard 2.1 library consisting of the library stuff, and a .net core 3.1 application for the command line support. Also, I migrated to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/xelement-class-overview for xml parsing.

So a PR with these changes would be feasible.

**Comment by thisisthekap** [comment]
So by having the library in .net standard 2.0, we could easily accomplish cross platform compatibility, while still maintaining the win forms client.

**Comment by preseverence** [comment]
I understand using .net core to run it on non-Windows systems. But this is not an answer for workflow of CLI util. Something like this maybe:

1. Run it and provide path to mapping file in command line
1. Provide obfuscated stacktrace via STD input
1. Read deobfuscated stacktrace via STD output

Yes. separating processing code and the UI to different assemblies will be the first step.

P.S. Anyway NanoXml still will be used.

**Comment by thisisthekap** [comment]
I am afraid that I can't use NonoXml in .net standard.

**Comment by preseverence** [comment]
It can be replatformed too.

For now I am not certain that the Obfuscar (and, thus, the Parser) is widely used.

**Comment by thisisthekap** [comment]
If NanoXml is replatformed (and eventually available as nuget), I would take care of the separation process.

**Comment by preseverence** [comment]
NanoXml is still counted as internal (this way it is not available as sourcecode even here). So I doubt that it will be nuget package too.

But everything can be solved if desired.

**Comment by thisisthekap** [comment]
@preseverence You could publish NanoXml as public nuget (the dll is public in this repository anyways) while keeping the sourcecode of NanoXml private.

**Comment by preseverence** [comment]
It is public here, but protected with BrokenEvent Dependency License.

* Use Binaries [list of libs including NanoXml] not as part of the Project [obfuscar mapping parser] or as part of another project.

Which means that it can't be used for another projects freely.

I didn't decide yet if I wish to change that.

**Comment by thisisthekap** [comment]
If ok for you, I will do the separation on a fork of our repo with using XElement for the xml parsing part for now.

**Comment by preseverence** [comment]
I will try to perform separating by my own (including retargeting that new lib and the NanoXml to .net standart). Then maybe will leave .netcore CLI app for you via PRs or direct write access to this repo.

Logic and UI is a bit mixed here. I want to keep the structure the same as now as far as I could.

**Comment by preseverence** [comment]
@thisisthekap I did separation of logic and UI and added .net standard version of NanoXml.

But the engine will not be changed to .net standard within the UI version of the Parser.

So you can:

* work in your own fork
  * use `XElement` as you wanted
  * or use .net standard version of NanoXml
* or we can create separate .net standard project for engine with relinked code files which you can use for CLI app with keeping this repo as main. This way you should add your CLI workflow via PR.
